### ISSUE TITLE
Embedding images and vectors

### ISSUE THREAD

**Issue by udrzbarik** [joaomarcelofm/figma-plugin-template-vue#4]
Hello, I'm trying to embed the images/svgs with this setup, but it seems to fail somehow. Works well when I hard past SVG tags into the template. Is there a special way to do this either with Vue/this specific setup?

Thanks!

**Comment by joaomarcelofm** [comment]
Do you mean images in your components in Figma's canvas?
The components will render HTML normally, so it should be as simple as `<img src="...">`. If it's the canvas, you need to convert it to an [accepted object](https://www.figma.com/plugin-docs/working-with-images/).

Feel free to drop a sample code, it'll make it easier to help.
